services:
  postgres:
    image: postgres:16-alpine
    container_name: pos_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pos_system
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
